---
title: "NYC Restaurant Inspection"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)

library(plotly)
library(flexdashboard)

data(rest_inspec)

rest_inspec_df =
  rest_inspec |> 
  select(boro, cuisine_description, score, zipcode) |> 
  filter(boro == "MANHATTAN") |> 
  drop_na(score) |> 
  mutate(
    zipcode = as.character(zipcode),
    cuisine_description = as.factor(cuisine_description),
    cuisine_description = ifelse(cuisine_description == "Latin (Cuban, Dominican, Puerto Rican, South & Central American)", paste("Latin American"), paste(cuisine_description))
      ) 
```

Column {data-width=600}
-----------------------------------------------------------------------

### Different types of cuisine and their restaurant scores in Manhattan by Zip Code

```{r}
rest_inspec_df |> 
  plot_ly(
    x = ~cuisine_description, y = ~score, color = ~zipcode,
    type = "scatter", mode = "markers", colors = "viridis") |> 
    layout(xaxis = list(title = 'Type of Cuisine'), 
           yaxis = list(title = 'Score of Restaurant'),
           legend = list(title = list(text ='Zip Code')))
```

Column {data-width=400}
-----------------------------------------------------------------------

### Different types of cuisine and their restaurant scores in Manhattan

```{r}
rest_inspec_df |> 
  plot_ly(
    y = ~score, color = ~cuisine_description, type = "box", colors = "viridis") |> 
    layout(xaxis = list(title = 'Type of Cuisine'), 
           yaxis = list(title = 'Score of Restaurant'))
```

### Most popular types of cuisine in Manhattan

```{r}
rest_inspec_df |> 
    count(cuisine_description) |>  
    filter(n > 1000) |>
    mutate(cuisine_description = fct_reorder(cuisine_description, n)) |> 
    plot_ly(
      x = ~cuisine_description, y = ~n, type = "bar", 
      color = ~cuisine_description, colors = "viridis") |> 
    layout(xaxis = list(title = 'Type of Cuisine'), 
           yaxis = list(title = 'Number of Restaurants'))
```

